/var/spool/slurmd/job00106/slurm_script: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
Start Training ...................................

          Initializing TSN with base model: BNInception.
          TSN Configurations:
              input_modality:     RGBDiff
              num_segments:       7
              new_length:         5
              consensus_module:   avg
              dropout_ratio:      0.8
               
Load and modify the standard model FC output layer
Dropout Layer added and The modified linear layer is : Linear(in_features=1024, out_features=101, bias=True)
Done. Loading and Modifying 
 ---------------------------------------------------
Converting the ImageNet model to RGBDiff model
The modified 1st layer is Conv2d(15, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
Done. RGBDiff model is ready.
---------------------------------------------------
group: first_conv_weight has 1 params, lr_mult: 1, decay_mult: 1
group: first_conv_bias has 1 params, lr_mult: 2, decay_mult: 0
group: normal_weight has 69 params, lr_mult: 1, decay_mult: 1
group: normal_bias has 69 params, lr_mult: 2, decay_mult: 0
group: BN scale/shift has 2 params, lr_mult: 1, decay_mult: 0
---------------------------------------------------
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532582123400/work/aten/src/THC/THCCachingHostAllocator.cpp line=271 error=2 : out of memory
Epoch: [0][0/150], lr: 0.00100	Time 118.337 (118.337)	Data 61.065 (61.065)	Loss 4.6148 (4.6148)	Acc@1 0.000 (0.000)	Acc@5 6.250 (6.250)
Traceback (most recent call last):
  File "main.py", line 390, in <module>
    main()
  File "main.py", line 144, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 193, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/alex039u2/data/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/alex039u2/data/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/alex039u2/data/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 133, in _worker_manager_loop
    batch = pin_memory_batch(batch)
  File "/home/alex039u2/data/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 200, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/home/alex039u2/data/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 200, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/home/alex039u2/data/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 194, in pin_memory_batch
    return batch.pin_memory()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1532582123400/work/aten/src/THC/THCCachingHostAllocator.cpp:271

End of Training .................................
